# UI Lovelace

title: Huntington Beach
views:
  - title: Home
    id: home
    icon: mdi:home
    cards:
    - type: 'custom:sun-card'
  - title: Living Room
    id: livingroom
    icon: mdi:sofa
    # cards:
    #   - title: Sundeck
    #     type: entities
    #     show_header_toggle: true
    #     entities:
    #       - entity: group.outside_lights_view
    #         name: Sundeck Lights
  - title: Office
    id: office
    icon: mdi:desktop-classic
