# UI Lovelace

background: var(--background-image)

title: Huntington Beach
views:
  - title: Home
    id: home
    icon: mdi:home
    cards:
    - type: vertical-stack
      cards:
      - type: custom:sun-card
      - type: custom:weather-card
        entity: weather.forecast_home
        current: true
        details: true
        forecast: true
        hourly_forecast: false
        number_of_forecasts: 2
      - type: entities
        title: Lights
        show_header_toggle: false
        entities:
          - type: section
            label: Living Room Lights
          - entity: group.livingroomlights
          # - entity: light.entry_hallway
          # - type: section
          #   label: Office Lights
          # - entity: light.desk
          # - type: section
          #   label: Bedroom Lights
          # - entity: light.nightstand
          # - entity: light.dresser
    - type: vertical-stack
      cards:
      - type: entities
        title: Monthly Power Consumption
        entities:
          - name: Server
            entity: sensor.smartplug_server_1mon
          - name: PC
            entity: sensor.smartplug_pc_1mon
          - name: Carlos
            entity: sensor.smartplug_carlos_1mon
          - name: Extra
            entity: sensor.smartplug_extra_1mon
      - type: entities
        title: SmartPlugs
        show_header_toggle: false
        entities:
          - type: conditional
            conditions:
              - entity: switch.smartplug_server
                state: 'on'
            row:
              type: button
              entity: switch.smartplug_server
              name: Server
              action_name: Turn Off
              tap_action:
                action: call-service
                service: switch.turn_off
                target:
                  entity_id: switch.smartplug_server
                confirmation:
                  text: Are you sure you want to turn off the switch?
          - type: conditional
            conditions:
              - entity: switch.smartplug_server
                state: 'off'
            row:
              type: button
              entity: switch.smartplug_server
              name: Server
              action_name: Turn On
              tap_action:
                action: call-service
                service: switch.turn_on
                target:
                  entity_id: switch.smartplug_server
                confirmation:
                  text: Are you sure you want to turn on the switch?
          - type: conditional
            conditions:
              - entity: switch.smartplug_pc
                state: 'on'
            row:
              type: button
              entity: switch.smartplug_pc
              name: PC
              action_name: Turn Off
              tap_action:
                action: call-service
                service: switch.turn_off
                target:
                  entity_id: switch.smartplug_pc
                confirmation:
                  text: Are you sure you want to turn off the switch?
          - type: conditional
            conditions:
              - entity: switch.smartplug_pc
                state: 'off'
            row:
              type: button
              entity: switch.smartplug_pc
              name: PC
              action_name: Turn On
              tap_action:
                action: call-service
                service: switch.turn_on
                target:
                  entity_id: switch.smartplug_pc
                confirmation:
                  text: Are you sure you want to turn on the switch?
          - type: conditional
            conditions:
              - entity: switch.smartplug_extra
                state: 'on'
            row:
              type: button
              entity: switch.smartplug_extra
              name: Extra
              action_name: Turn Off
              tap_action:
                action: call-service
                service: switch.turn_off
                target:
                  entity_id: switch.smartplug_extra
                confirmation:
                  text: Are you sure you want to turn off the switch?
          - type: conditional
            conditions:
              - entity: switch.smartplug_extra
                state: 'off'
            row:
              type: button
              entity: switch.smartplug_extra
              name: Extra
              action_name: Turn On
              tap_action:
                action: call-service
                service: switch.turn_on
                target:
                  entity_id: switch.smartplug_extra
                confirmation:
                  text: Are you sure you want to turn on the switch?
          - type: conditional
            conditions:
              - entity: switch.smartplug_carlos
                state: 'on'
            row:
              type: button
              entity: switch.smartplug_carlos
              name: Carlos
              action_name: Turn Off
              tap_action:
                action: call-service
                service: switch.turn_off
                target:
                  entity_id: switch.smartplug_carlos
                confirmation:
                  text: Are you sure you want to turn off the switch?
          - type: conditional
            conditions:
              - entity: switch.smartplug_carlos
                state: 'off'
            row:
              type: button
              entity: switch.smartplug_carlos
              name: Carlos
              action_name: Turn On
              tap_action:
                action: call-service
                service: switch.turn_on
                target:
                  entity_id: switch.smartplug_carlos
                confirmation:
                  text: Are you sure you want to turn on the switch?
    - type: vertical-stack
      cards:
      - type: custom:mini-graph-card
        name: Server Power Draw - This Week
        icon: mdi:lightning-bolt
        color_thresholds_transition: smooth
        decimals: 0
        hours_to_show: 84
        points_per_hour: 6
        line_width: 2
        lower_bound: 0
        show:
          extrema: true
          average: true
          state: false
        entities:
          - entity: sensor.smartplug_server_1min
            aggregate_func: avg
            show_points: false
      - type: custom:mini-graph-card
        name: PC Power Draw - This Week
        icon: mdi:lightning-bolt
        color_thresholds_transition: smooth
        decimals: 0
        hours_to_show: 84
        points_per_hour: 6
        line_width: 2
        lower_bound: 0
        show:
          extrema: true
          average: true
          state: false
        entities:
          - entity: sensor.smartplug_pc_1min
            aggregate_func: avg
            show_points: false
      - type: custom:mini-graph-card
        name: Carlos Power Draw - This Week
        icon: mdi:lightning-bolt
        color_thresholds_transition: smooth
        decimals: 0
        hours_to_show: 84
        points_per_hour: 6
        line_width: 2
        lower_bound: 0
        show:
          extrema: true
          average: true
          state: false
        entities:
          - entity: sensor.smartplug_carlos_1min
            aggregate_func: avg
            show_points: false
      - type: custom:mini-graph-card
        name: Extra Power Draw - This Week
        icon: mdi:lightning-bolt
        color_thresholds_transition: smooth
        decimals: 0
        hours_to_show: 84
        points_per_hour: 6
        line_width: 2
        lower_bound: 0
        show:
          extrema: true
          average: true
          state: false
        entities:
          - entity: sensor.smartplug_extra_1min
            aggregate_func: avg
            show_points: false
      - type: entities
        show_header_toggle: false
        entities:
        - entities:
          - input_select.theme
          - input_boolean.theme_alternative
          head:
            entity: input_boolean.dark_mode
            name: Dark mode
          type: custom:fold-entity-row
  - title: Network
    id: network
    icon: mdi:router-network
    cards:
    - type: vertical-stack
      cards:
      - type: entities
        name: Connectivity
        show_header_toggle: false
        entities:
        - name: WAN Status
          entity: binary_sensor.unifi_dream_machine_wan_status
        - name: Uptime
          entity: sensor.udm_uptime_formatted
      - type: custom:mini-graph-card
        name: DMP KiB/s
        icon: mdi:router-wireless
        hours_to_show: 24
        points_per_hour: 3
        line_width: 2
        show:
          state: true
          labels: hover
          points: hover
        entities:
          - entity: sensor.unifi_dream_machine_kib_s_received
            name: KiB/s received
            show_points: false
          - entity: sensor.unifi_dream_machine_kib_s_sent
            name: KiB/s sent
            show_points: false
      - type: custom:mini-graph-card
        name: DMP Packets/s
        icon: mdi:router-wireless
        hours_to_show: 24
        points_per_hour: 3
        line_width: 2
        show:
          state: true
          labels: hover
          points: hover
        entities:
          - entity: sensor.unifi_dream_machine_packets_s_received
            name: Packets/s received
            show_points: false
          - entity: sensor.unifi_dream_machine_packets_s_sent
            name: Packets/s sent
            show_points: false
    - type: vertical-stack
      cards:
      - type: entities
        title: People
        show_header_toggle: false
        entities:
          - entity: person.brian
          - entity: person.carlos
          # - entity: person.tony
