- alias: 'Frontend: turn on dark mode'
  trigger:
    - platform: sun
      event: sunset
  condition: "{{ is_state('input_boolean.dark_mode', 'off') }}"
  action:
    entity_id: input_boolean.dark_mode
    service: input_boolean.turn_on

- alias: 'Frontend: turn on light mode'
  trigger:
    - platform: sun
      event: sunrise
  condition: "{{ is_state('input_boolean.dark_mode', 'on') }}"
  action:
    entity_id: input_boolean.dark_mode
    service: input_boolean.turn_off

- alias: 'Frontend: change theme'
  trigger:
    - platform: state
      entity_id: input_select.theme
    - platform: state
      entity_id: input_boolean.dark_mode
    - platform: state
      entity_id: input_boolean.theme_alternative
    - platform: homeassistant
      event: start
  action:
    service: frontend.set_theme
    data:
      name: >
        {% if is_state('input_select.theme', 'dracula') %}
          Dracula
        {% else %}
          {% set which = 'dark' if is_state('input_boolean.dark_mode', 'on') else 'light' -%}
          {% set name = states('input_select.theme') -%}
          {% set suffix = '-alternative' if is_state('input_boolean.theme_alternative', 'on') else '' -%}
          ios-{{ which }}-mode-{{ name }}{{ suffix }}
        {% endif %}
