- alias: 'Frontend: turn on dark mode'
  trigger:
    - platform: sun
      event: sunset
  condition: "{{ is_state('input_boolean.dark_mode', 'off') }}"
  action:
    entity_id: input_boolean.dark_mode
    service: input_boolean.turn_on

- alias: 'Frontend: turn on light mode'
  trigger:
    - platform: sun
      event: sunrise
  condition: "{{ is_state('input_boolean.dark_mode', 'on') }}"
  action:
    entity_id: input_boolean.dark_mode
    service: input_boolean.turn_off

- alias: 'Frontend: change theme'
  trigger:
    - platform: state
      entity_id: input_boolean.dark_mode
    - platform: homeassistant
      event: start
  action:
    service: frontend.set_theme
    data:
      name: >
        {% if is_state('input_boolean.dark_mode', 'on') %}
          Dracula
        {% else %}
          ios-light-mode-blue-red
        {% endif %}
